export const TableItems = [
  {
    type: "Level of Expertise",
    "Freelance Market": "Low",
    "Remote Office": "Vetted Top Experts",
    "In-house": "Varies",
    Agencies: "Varies",
  },
  {
    type: "Dedicated Employee",
    "Freelance Market": false,
    "Remote Office": true,
    "In-house": true,
    Agencies: "Varies",
  },
  {
    type: "Fee",
    "Freelance Market": "$$",
    "Remote Office": "$$",
    "In-house": "$$$$",
    Agencies: "$$$$",
  },
  {
    type: "Client Service Team",
    "Freelance Market": false,
    "Remote Office": true,
    "In-house": false,
    Agencies: "Varies",
  },
  {
    type: "Performance Evaluation",
    "Freelance Market": false,
    "Remote Office": true,
    "In-house": "Varies",
    Agencies: false,
  },
  {
    type: "Outlined Solutions",
    "Freelance Market": false,
    "Remote Office": true,
    "In-house": "Varies",
    Agencies: "Varies",
  },
  {
    type: "Sprint/Goal Management",
    "Freelance Market": false,
    "Remote Office": true,
    "In-house": "Varies",
    Agencies: "Varies",
  },
  {
    type: "Tax & Legal Compliance Management",
    "Freelance Market": false,
    "Remote Office": true,
    "In-house": "Varies",
    Agencies: false,
  },
  {
    type: "Managed IT Support",
    "Freelance Market": false,
    "Remote Office": true,
    "In-house": "Varies",
    Agencies: false,
  },
];
